config/routes.rb
Rails.application.routes.draw do

  resources :activities
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments
    member do
      put "like", to: "posts#upvote"
    end
  end
  # Define Root URL
  root 'pages#index'
  
  # Define Routes for Pages
  get '/home' => 'pages#home' # override default routes.
  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/wzeet/:id' => 'posts#show'
  get '/wzeets' => 'pages#posts'
  get '/hashtag/:name', to: 'posts#hashtags'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  acts_as_votable
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 } # tweets are capped at 140 chars.
  default_scope -> { order(created_at: :desc) } # newest tweets / posts first
  has_attached_file :image, styles: { medium: "476x476>", thumb: "100x100>" }, dependent: :destroy
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.content.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end
  
  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear
    hashtags = self.content.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def new 
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id # assign the post to the user who created it.
        respond_to do |f|
            if (@post.save)
                f.html { redirect_to "", notice: "Post created!" }
            else
                f.html { redirect_to "", notice: "Error: Post Not Saved." }
            end
        end
    end
    def destroy
        @post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
    end
    def show
        @post = Post.find(params[:id])
    end
    def hashtags
        tag = Tag.find_by(name: params[:name])
        @posts = tag.posts
    end
    def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to "/user/" +  current_user.username
    end

    def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to redirect_to "/user/" +  current_user.username
    end
    
    private
    def post_params # allows certain data to be passed via form.
        params.require(:post).permit(:user_id, :content, :image)
        
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
    def render_with_hashtags(body)
        body.gsub(/#\w+/){|word| link_to word,"/hashtag/#{word.downcase.delete('#')}"}.html_safe
    end
end

app/views/posts/hashtags.html.erb
<div class="row">
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-image hide-panel-body">  
            <%= image_tag current_user.cover.url(:side), :class => "panel-image-preview" %>
          </div>
          <div class="panel-footer">
            <div class="row">
                <div class="col-sm-2">
                <%= image_tag current_user.avatar.url(:side), :class => "rounded-img home-avatar" %>
                </div>
                <div class="col-sm-10"><h4 style="text-align: left;padding-left: 10px;margin-top: 0px;"><%=link_to current_user.fullname, "/user/"+current_user.username %><br>(@<%= current_user.username %>)</h4></div>
                <div class="col-sm-12" style="margin-top: 10px;">
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;"><%= link_to "WZEETS", "/wzeets", :style => "font-size: 80%; opacity: 0.7;" %><br>
                    <h6 style="color: #0084B4; font-size: 200%; padding-left: 7px;"><%= number_to_human(current_user.posts.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">FOLLOWERS<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= number_to_human(current_user.followers.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;margin-left:50px;margin-right:50px;">FOLLOWING<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= number_to_human(current_user.following.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                </div> 
            </div>

          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Trends</h5>
             <% Tag.first(10).each do |t| %>
               <% if t.posts.count == 0 %>
                 <%= t.destroy %>
               <% end %> 
               <p><a href="/hashtag/<%= t.name %>">#<%= t.name %></a></p>
               <p><b><%= t.posts.count %> Posts</b></p>
             <% end %> 
          </div>
        </div>
    </div>
    <div class="col-xs-6">
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
              <%= image_tag @p.user.avatar.url(:thumb), :class => "rounded-img" %>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).fullname %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= render_with_hashtags(@p.content) %><br><%= image_tag @p.image.url(:medium) if @p.image.exists? %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links" style="margin-bottom: 0px; margin-top: 5px;">
                <span style="margin-right: 75px;"><i class="fa fa-comment" aria-hidden="true" style="bg-color:#337ab7;"><%= @p.comments.count %></i></span>
                <span style="margin-right: 75px;"><%= link_to @p.get_upvotes.size, like_post_path(@p), method: :put, :class => "fa fa-heart" %></span>
                <% if @p.user.email == current_user.email %>
                <span style="margin-right: 75px;"><%= link_to "", post_path(@p), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o" %></span>
                <% end %>
                <a href=<%= "/wzeet/" +  @p.id.to_s %>>View conversation</a>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/icon.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <p style="opacity: 0.5; font-size: 90%;">© 2016 WZitter  About  Help  Terms  Privacy  Cookies  Ads Info  Brand  Blog  Status  Apps  Jobs  Advertise  Businesses  Media  Developers</p>
          </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-xs-3">
      
        <div class="panel panel-default">
          <div class="panel-image hide-panel-body">  
            <%= image_tag current_user.cover.url(:side), :class => "panel-image-preview" %>
          </div>
          <div class="panel-footer">
            <div class="row">
                <div class="col-sm-2">
                <%= image_tag current_user.avatar.url(:side), :class => "rounded-img home-avatar" %>
                </div>
                <div class="col-sm-10"><h4 style="text-align: left;padding-left: 10px;margin-top: 0px;"><%=link_to current_user.fullname, "/user/"+current_user.username %><br>(@<%= current_user.username %>)</h4></div>
                <div class="col-sm-12" style="margin-top: 10px;">
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;"><%= link_to "WZEETS", "/wzeets", :style => "font-size: 80%; opacity: 0.7;" %><br>
                    <h6 style="color: #0084B4; font-size: 200%; padding-left: 7px;"><%= number_to_human(current_user.posts.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">FOLLOWERS<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= number_to_human(current_user.followers.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;margin-left:50px;margin-right:50px;">FOLLOWING<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= number_to_human(current_user.following.count , :format => '%n%u', :units => { :thousand => 'K' }) %></h6>
                  </div>
                </div>
            </div>

          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Trends</h5>
             <% Tag.first(10).each do |t| %>
               <% if t.posts.count == 0 %>
                 <%= t.destroy %>
               <% end %> 
               <p><a href="/hashtag/<%= t.name %>">#<%= t.name %></a></p>
               <p><b><%= number_to_human(t.posts.count , :format => '%n%u', :units => { :thousand => 'K' }) %> Posts</b></p>
             <% end %> 
          </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-1">
              <%= image_tag User.find(@post.user_id).avatar.url(:side), :class => "rounded-img" %>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@post.user_id).username %>"><%= User.find(@post.user_id).fullname %></a></span><span class="username"><b><%= " @"+User.find(@post.user_id).username %></b></span> <span class="post-creation">- <%= @post.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= @post.content %><br><%= image_tag @post.image.url(:medium) if @post.image.exists? %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links" style="margin-bottom: 0px; margin-top: 5px;">
                <span style="margin-right: 75px;"><i class="fa fa-comment" aria-hidden="true" style="bg-color:#337ab7;"><%= @post.comments.count %></i></span>
                
                <span style="margin-right: 75px;"><%= link_to @post.get_upvotes.size, like_post_path(@post), method: :put, :class => "fa fa-heart" %></span>
                <% if @post.user.email == current_user.email %>
                <span style="margin-right: 75px;"><%= link_to "", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o" %></span>
                <% end %>
              </p>
            </div>
            
          </div>
        </div>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <% if user_signed_in? %>
            <%= render "comments/form" %>
            
            <%= render @post.comments %>
            <% else %>
            Please Login
            <% end %>
          </div>
        </div>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/icon.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <p style="opacity: 0.5; font-size: 90%;">© 2016 WZitter  About  Help  Terms  Privacy  Cookies  Ads Info  Brand  Blog  Status  Apps  Jobs  Advertise  Businesses  Media  Developers</p>
          </div>
        </div>
    </div>
</div>